export const mockRequests = [
  {
    id: 1,
    status: "new",
    tenantName: "יוסי כהן",
    projectName: "מגדלי הים התיכון",
    apartmentNumber: "501",
    issueDescription: "נזילה מהתקרה במטבח",
    images: ["/placeholder.svg?height=100&width=100"],
    submissionDate: "15/03/2023",
    warrantyPeriod: "bedek",
    warrantyEndDate: "15/03/2024",
    urgencyLevel: "urgent",
    additionalNotes: "נא לטפל בהקדם האפשרי",
    category: "אינסטלציה",
    location: "מטבח",
    tenantComments: "המים מטפטפים כל הזמן, גם כשהברזים סגורים",
    assignedContractor: {
      name: 'חברת השרברבים בע"מ',
      contact: "050-1234567",
    },
    estimatedResolutionDate: "20/03/2023",
  },
  {
    id: 2,
    status: "in-progress",
    tenantName: "רחל לוי",
    projectName: "פסגות ירושלים",
    apartmentNumber: "302",
    issueDescription: "בעיה בחשמל בסלון",
    images: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    submissionDate: "20/04/2023",
    warrantyPeriod: "warranty",
    warrantyEndDate: "20/04/2025",
    urgencyLevel: "normal",
    additionalNotes: "ממתין לתגובת הקבלן",
    category: "חשמל",
    location: "סלון",
    tenantComments: "השקעים בסלון לא עובדים, אבל האור דולק",
    assignedContractor: {
      name: "אלקטרו-פיקס",
      contact: "052-9876543",
    },
    estimatedResolutionDate: "25/04/2023",
  },
  {
    id: 3,
    status: "resolved",
    tenantName: "דוד מזרחי",
    projectName: "נווה צדק החדשה",
    apartmentNumber: "1205",
    issueDescription: "סדקים בקירות חדר השינה",
    images: [],
    submissionDate: "10/05/2023",
    warrantyPeriod: "out-of-warranty",
    warrantyEndDate: "01/01/2023",
    urgencyLevel: "critical",
    additionalNotes: "טופל על ידי קבלן חיצוני",
    category: "קירות",
    location: "חדר שינה",
    tenantComments: "הסדקים מתרחבים מיום ליום, אני חושש שזו בעיה מבנית",
    assignedContractor: {
      name: 'בוני הארץ בע"מ',
      contact: "03-5555555",
    },
    estimatedResolutionDate: "15/05/2023",
  },
  {
    id: 4,
    status: "new",
    tenantName: "שרה אברהם",
    projectName: "גני תקווה הירוקה",
    apartmentNumber: "701",
    issueDescription: "רטיבות בקיר המקלחת",
    images: ["/placeholder.svg?height=100&width=100"],
    submissionDate: "01/01/2024",
    warrantyPeriod: "bedek",
    warrantyEndDate: "01/01/2025",
    urgencyLevel: "urgent",
    additionalNotes: "נדרשת בדיקה דחופה",
    category: "אינסטלציה",
    location: "חדר רחצה",
    tenantComments: "הרטיבות מתפשטת לכיוון חדר השינה",
    assignedContractor: {
      name: "מומחי האינסטלציה",
      contact: "054-1234567",
    },
    estimatedResolutionDate: "05/01/2024",
  },
  {
    id: 5,
    status: "in-progress",
    tenantName: "מיכל ברק",
    projectName: "מגדלי הים התיכון",
    apartmentNumber: "1102",
    issueDescription: "דלת הכניסה לא נסגרת כראוי",
    images: ["/placeholder.svg?height=100&width=100"],
    submissionDate: "15/01/2024",
    warrantyPeriod: "warranty",
    warrantyEndDate: "15/01/2026",
    urgencyLevel: "normal",
    additionalNotes: "הוזמן נגר",
    category: "נגרות",
    location: "כניסה",
    tenantComments: "הדלת חורקת ולא ננעלת כראוי",
    assignedContractor: {
      name: "נגריית האומן",
      contact: "053-9876543",
    },
    estimatedResolutionDate: "20/01/2024",
  },
  {
    id: 6,
    status: "transferred",
    tenantName: "אבי לוין",
    projectName: "פסגות ירושלים",
    apartmentNumber: "405",
    issueDescription: "בעיות במיזוג האוויר",
    images: ["/placeholder.svg?height=100&width=100"],
    submissionDate: "20/01/2024",
    warrantyPeriod: "bedek",
    warrantyEndDate: "20/01/2025",
    urgencyLevel: "critical",
    additionalNotes: "הועבר לטיפול טכנאי מיזוג",
    category: "מיזוג אוויר",
    location: "כל הדירה",
    tenantComments: "המזגן לא מקרר ומשמיע רעשים חזקים",
    assignedContractor: {
      name: "קור וחום מערכות",
      contact: "052-1234567",
    },
    estimatedResolutionDate: "25/01/2024",
  },
]

